### ISSUE TITLE
Disabling Reading List on Your Own Works

### ISSUE THREAD

**Issue by Ubuntuify** [jsmnbom/ao3-enhancements#23]
Greetings! It's me.

I've noticed your call for beta testers, so I have some criticisms first.

I would like the Reading List to be disabled on the works you made yourself as I do not usually read my works and I would see some people's Reading List getting cluttered with their own works.

Otherwise, I haven't found that many problems with the new extension, but I would really like the subscribe and kudos preview to be re-added. No pressure though!

'Til we meet again! 😃

<sup>I'll be sure to provide a bigger and more extensive review of the new update soon.</sup>

**Comment by jsmnbom** [comment]
Thanks a lot for trying out the beta. I'm currently fixing some bugs caused by AO3 updates, but I will definitely keep this in mind. For now you could add your own works as "On hold" or similar, and they shouldn't get changed to "Currently Reading" (tho i'm gonna have to double check that).

In terms of kudos and subscribe preview, it is very unlikely that will ever get re-added. It caused a lot of issues including but not limited to: excessive AO3 requests, users getting rate-limited, adding a ton of works to users' history as well as adding hits to works even tho the user never visited it.

**Comment by RyanGamingXbox** [comment]
Oh, that makes sense. AO3 doesn't really have an available API so it would make sense that it would make excessive requests.

I haven't been using AO3 recently, so I don't have much feedback yet. But I do say that the Reading List has decreased my tabs. I can finally be somewhat free from this tab hell. I've literally been force-killing Chrome just to move my tabs to new restarts of my computer. I pledge that these tabs will be gone by the end of the week. But that's probably not going to happen.

**Comment by jsmnbom** [comment]
"Fixed" in v0.5. (Reading List feature is completely removed.)
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
