### ISSUE TITLE
Is this still being updated or maintained?

### ISSUE THREAD

**Issue by LiftedStarfish** [jsmnbom/ao3-enhancements#42]
There hasn't been a new commit since September of 2021, and no new PR have been merged or closed since then. If this isn't being maintained or updated, it really should say so on the main readme so that people know that they are using unmaintained software.

**Comment by jsmnbom** [comment]
Currently this isn't being maintained due to IRL stuff coming in the way, but I'm hoping to return to it soon.

**Comment by jsmnbom** [comment]
Welp, soon turned out to be 1,5 years later, but in case anyone is following this thread, I'm currently working on it in the https://github.com/jsmnbom/ao3-enhancements/tree/dev branch. It removes the (in progress but horribly broken) reading list feature, and instead focuses on just updating addressing issues. Furthermore it updates to MV3 making it compatible with chrome after June :D

**Comment by jsmnbom** [comment]
Finally got around to making a release :D
