### ISSUE TITLE
reading list 

### ISSUE THREAD

**Issue by belenosblack** [jsmnbom/ao3-enhancements#76]
Just wondering if the reading list is coming back? It disappeared sometime yesterday.

**Comment by jsmnbom** [comment]
Unfortunately it has been removed as it (esp the sync) was quite buggy, and it also proved to be a big blocker for me being able to make a timely release. If you do a options export you should still have the data from the reading list, tho i admit not in a particular user friendly format. Alternatively (AFTER making a backup the current data) downgrade to a 0.4 beta and take screenshots or similar of the data you'd like to preserve. Sorry for the annoyance.

See rest of the release notes for 0.5 here: https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4

**Comment by belenosblack** [comment]
Understood. Do you think a simpler version would make a come back eventually? Perhaps just the READ (completed and currently reading) and DROPPED, I really enjoyed knowing what I had read (and read and didn't like), I think i had just under 4000 books sorted like that since it became an feature.

**Comment by jsmnbom** [comment]
I hope so, but no promises atm. Maybe in a different form. I'm working on something that works on all sites rather than just AO3 but it wouldn't be only a browser extension but rather a self hosted app.

A really really simple version of reading list could perhaps be implemented, but dunno if I have the motivation atm but we'll see :3
